[package]
name = "textr"
version = "0.1.0"
edition = "2021"
description = "TeX-inspired text formatting app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-normalization = "0.1.22"
nalgebra-glm = "0.18.0"
log = "0.4.20"
textwrap = "0.16.0"
env_logger = "0.11.3"
itertools = "0.12.0"
wgpu = "0.19.3"
pollster = "0.3.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
winit = "0.29.15"
anyhow = "1.0.79"
freetype-rs = "0.36.0"
clap = { version = "4.5.1", features = ["derive"] }
crossbeam-channel = "0.5.12"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

[profile.release]
debug = true

[package.metadata.bundle]
name = "TeXtr"
identifier = "io.github.ghovax.textr"
icon = []
version = "0.1.0"
resources = []

[profile.dev]
opt-level = 1
