[package]
name = "textr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freetype-rs = "0.34.1"
unicode-normalization = "0.1.22"
# glad-gl = { path = "./build/glad-gl" }
nalgebra-glm = "0.18.0"
lazy_static = "1.4.0"
log = "0.4.20"
textwrap = "0.16.0"
chrono = "0.4.31"
env_logger = "0.10.1"
itertools = "0.12.0"
color-art = "0.3.7"
glow = { version = "0.13.0" }
# gl = "0.14.0"
regex = "1.10.2"
sdl2 = { version = "0.36.0", features = ["bundled"] }

[profile.release]
debug = true

[package.metadata.bundle]
name = "TeXtr"
identifier = "io.github.ghovax.textr"
icon = []
version = "0.1.0"
resources = []

[profile.dev]
opt-level = 1
