[package]
name = "textr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freetype-rs = "0.34.1"
glfw = "0.54.0"
unicode-normalization = "0.1.22"
glad-gl = { path = "./build/glad-gl" }
nalgebra-glm = "0.18.0"
lazy_static = "1.4.0"
log = "0.4.20"
env_logger = "0.10.1"
textwrap = "0.16.0"
chrono = "0.4.31"
