[package]
name = "textr"
version = "0.1.0"
edition = "2021"
description = "TeX-inspired text formatting app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-normalization = "0.1.22"
log = "0.4.20"
textwrap = { version = "0.16.0", features = ["hyphenation"] }
env_logger = "0.11.3"
itertools = "0.12.0"
pollster = "0.3.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
clap = { version = "4.5.3", features = ["derive"] }
image-compare = "0.4.0"
rusttype = { version = "0.9.3", features = ["gpu_cache"] }
hyphenation = "0.8.4"
glium = "0.32.0"
image = { version = "0.25.0", default-features = false, features = ["png"] }
anyhow = "1.0.81"

[profile.release]
debug = true

[profile.dev]
opt-level = 1
